### ISSUE TITLE
Если Windows больше нет

### ISSUE THREAD

**Issue by AngelinaBar** [kalininei/CFDCourse23#1]
Так вышло, что windows у меня больше нет (есть Ubuntu) :( Скачала Visual Studio Code, слева на чёрном фоне была иконка source control, по совету оттуда (первый шаг совпал с вашим гайдом) установила git, а дальше шаги расходятся: там предлагается 2 пути: открыть папку, содержащую репозиторий git или клонировать его по URL-адресу, но про cmake там ничего нет...смотрю здесь: https://code.visualstudio.com/docs/sourcecontrol/overview .Кажется, я что-то делаю не так...Немного в отчаянии:(

**Comment by kalininei** [comment]
Надо, полагать, проблему решили?

**Comment by AngelinaBar** [comment]
Да, всё нормально

**Comment by AngelinaBar** [comment]
Сделала всё заново: 
1) установила git (~$ git --version; git version 2.34.1)
2) установила Сmake (~$ cmake --version; cmake version 3.22.1) (из ubuntu software..меня немного смутило windows в ссылке (может и зря), поэтому решила поискать на том же сайте что-то для линукс, ссылка работает только до releases, дальше ошибка 404, что скачивать там я не понимаю)
3) склонировала по URL репозиторий в заранее созданную папку
4) Далее проделала шаг 1.2 из readme (Generating done, Configuring done,- эти строчки были)
5) пытаюсь запустить poisson.cpp.. ничего не выходит (пишет: "fatal error: common.hpp: Нет такого файла или каталога", но он лежит там, где и должен) вывод: ничего не собралось :(

**Comment by kalininei** [comment]
1.Незнаю, с какого сайта вы ставили cmake. Мне всегда казалось, что в убунте всё ставится через
> sudo apt-get install cmake
Ну впрочем, если в результате ваших манипуляций симейк вызывается, то всё нормально

2. Вы должны сделать такую последовательность команд (Начиная с самого начала)

> git clone http://github.com/kalininei/CFDCourse23
> cd CFDCourse23
> mkdir build
> cd build
> cmake ..
> make
> cd bin
> ./poisson

**Comment by AngelinaBar** [comment]
Также собиралось:) видимо дело в том, что я не умею пользоваться Visual Studio Code

**Comment by kalininei** [comment]
Я тоже не умею им пользоваться.
Но сейчас попробовал открыть папку с проектом через vscode, и всё настрилось само и компилируется через него.
Главное, чтобы открывать именно корневую папку проекта, чтобы он увидел корневой сборочный скрипт.

**Comment by AngelinaBar** [comment]
в VS Code слева, где идёт перечисление папок, 
.vscode
    ()launch.json и ()task.json 
CFDCourse23
   build, lib, progs + файл для Cmake и ещё что-то
Мне же нужно запускать то, что лежит в папке progs?

**Comment by kalininei** [comment]
Вам нужно открыть папку CFDCourse23.
Потом сконфигурировать cmake
![image](https://user-images.githubusercontent.com/5234858/202163932-3a53a62f-93c6-4ee5-987e-3cac16a558f4.png)

Потом собрать проект
![image](https://user-images.githubusercontent.com/5234858/202164417-8303d1a1-0235-4475-8446-a6f83804499d.png)

Потом запустить из терминала бинарник
![image](https://user-images.githubusercontent.com/5234858/202164684-01af0b3b-2bc7-45b8-8e2c-e0588f12a147.png)

**Comment by AngelinaBar** [comment]
Если нет предложения сконфигурировать проект..как на первом скрине, это может означать что у меня чего-то не хватает для этой команды? или во вкладке view->command palette-> CMake: configure эквивалентная команда?

**Comment by kalininei** [comment]
Да, вроде эквивалентная. Если у вас симейк нормально стоит.

**Comment by AngelinaBar** [comment]
Когда я запускаю эту программу у меня запрашивается СMakeLists.txt я должна указать тот, что лежит в папке CFDCourse23, так? Я так сделала и у меня вне папки СFDCourse23 появилась папка build

**Comment by kalininei** [comment]
Вы, значит, не из той папки работаете. Я вам сказал, откройте папку CFDCourse23 в vscode (File->Open Folder)
build должен появляться в CFDCourse23

**Comment by AngelinaBar** [comment]
Спасибо:))) получилось
